export const timezoneData = [{ timezoneCode: 'AF', timezoneName: 'Afghanistan Asia/Kabul', utcOffset: 'UTC +04:36' },
{ timezoneCode: 'AL', timezoneName: 'Albania Europe/Tirane', utcOffset: 'UTC +01:19' },
{ timezoneCode: 'DZ', timezoneName: 'Algeria Africa/Algiers', utcOffset: 'UTC +00:12' },
{ timezoneCode: 'AS', timezoneName: 'American Samoa Pacific/Pago_Pago', utcOffset: 'UTC +12:37' },
{ timezoneCode: 'AD', timezoneName: 'Andorra Europe/Andorra', utcOffset: 'UTC +00:06' },
{ timezoneCode: 'AO', timezoneName: 'Angola Africa/Luanda', utcOffset: 'UTC +00:13' },
{ timezoneCode: 'AI', timezoneName: 'Anguilla America/Anguilla', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'AQ', timezoneName: 'Antarctica Antarctica/Casey', utcOffset: 'UTC +00:00' },
{ timezoneCode: 'AQ', timezoneName: 'Antarctica Antarctica/Davis', utcOffset: 'UTC +00:00' },
{ timezoneCode: 'AQ', timezoneName: 'Antarctica Antarctica/DumontDUrville', utcOffset: 'UTC +09:48' },
{ timezoneCode: 'AQ', timezoneName: 'Antarctica Antarctica/Mawson', utcOffset: 'UTC +00:00' },
{ timezoneCode: 'AQ', timezoneName: 'Antarctica Antarctica/McMurdo', utcOffset: 'UTC +11:39' },
{ timezoneCode: 'AQ', timezoneName: 'Antarctica Antarctica/Palmer', utcOffset: 'UTC +00:00' },
{ timezoneCode: 'AQ', timezoneName: 'Antarctica Antarctica/Rothera', utcOffset: 'UTC +00:00' },
{ timezoneCode: 'AQ', timezoneName: 'Antarctica Antarctica/Syowa', utcOffset: 'UTC +03:06' },
{ timezoneCode: 'AQ', timezoneName: 'Antarctica Antarctica/Troll', utcOffset: 'UTC +00:00' },
{ timezoneCode: 'AQ', timezoneName: 'Antarctica Antarctica/Vostok', utcOffset: 'UTC +00:00' },
{ timezoneCode: 'AG', timezoneName: 'Antigua and Barbuda America/Antigua', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'AR', timezoneName: 'Argentina America/Argentina/Buenos_Aires', utcOffset: 'UTC -03:53' },
{ timezoneCode: 'AR', timezoneName: 'Argentina America/Argentina/Catamarca', utcOffset: 'UTC -04:23' },
{ timezoneCode: 'AR', timezoneName: 'Argentina America/Argentina/Cordoba', utcOffset: 'UTC -04:16' },
{ timezoneCode: 'AR', timezoneName: 'Argentina America/Argentina/Jujuy', utcOffset: 'UTC -04:21' },
{ timezoneCode: 'AR', timezoneName: 'Argentina America/Argentina/La_Rioja', utcOffset: 'UTC -04:27' },
{ timezoneCode: 'AR', timezoneName: 'Argentina America/Argentina/Mendoza', utcOffset: 'UTC -04:35' },
{ timezoneCode: 'AR', timezoneName: 'Argentina America/Argentina/Rio_Gallegos', utcOffset: 'UTC -04:36' },
{ timezoneCode: 'AR', timezoneName: 'Argentina America/Argentina/Salta', utcOffset: 'UTC -04:21' },
{ timezoneCode: 'AR', timezoneName: 'Argentina America/Argentina/San_Juan', utcOffset: 'UTC -04:34' },
{ timezoneCode: 'AR', timezoneName: 'Argentina America/Argentina/San_Luis', utcOffset: 'UTC -04:25' },
{ timezoneCode: 'AR', timezoneName: 'Argentina America/Argentina/Tucuman', utcOffset: 'UTC -04:20' },
{ timezoneCode: 'AR', timezoneName: 'Argentina America/Argentina/Ushuaia', utcOffset: 'UTC -04:33' },
{ timezoneCode: 'AM', timezoneName: 'Armenia Asia/Yerevan', utcOffset: 'UTC +02:58' },
{ timezoneCode: 'AW', timezoneName: 'Aruba America/Aruba', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'AU', timezoneName: 'Australia Antarctica/Macquarie', utcOffset: 'UTC +00:00' },
{ timezoneCode: 'AU', timezoneName: 'Australia Australia/Adelaide', utcOffset: 'UTC +09:14' },
{ timezoneCode: 'AU', timezoneName: 'Australia Australia/Brisbane', utcOffset: 'UTC +10:12' },
{ timezoneCode: 'AU', timezoneName: 'Australia Australia/Broken_Hill', utcOffset: 'UTC +09:25' },
{ timezoneCode: 'AU', timezoneName: 'Australia Australia/Darwin', utcOffset: 'UTC +08:43' },
{ timezoneCode: 'AU', timezoneName: 'Australia Australia/Eucla', utcOffset: 'UTC +08:35' },
{ timezoneCode: 'AU', timezoneName: 'Australia Australia/Hobart', utcOffset: 'UTC +09:49' },
{ timezoneCode: 'AU', timezoneName: 'Australia Australia/Lindeman', utcOffset: 'UTC +09:55' },
{ timezoneCode: 'AU', timezoneName: 'Australia Australia/Lord_Howe', utcOffset: 'UTC +10:36' },
{ timezoneCode: 'AU', timezoneName: 'Australia Australia/Melbourne', utcOffset: 'UTC +09:39' },
{ timezoneCode: 'AU', timezoneName: 'Australia Australia/Perth', utcOffset: 'UTC +07:43' },
{ timezoneCode: 'AU', timezoneName: 'Australia Australia/Sydney', utcOffset: 'UTC +10:04' },
{ timezoneCode: 'AT', timezoneName: 'Austria Europe/Vienna', utcOffset: 'UTC +01:05' },
{ timezoneCode: 'AZ', timezoneName: 'Azerbaijan Asia/Baku', utcOffset: 'UTC +03:19' },
{ timezoneCode: 'BS', timezoneName: 'Bahamas America/Nassau', utcOffset: 'UTC -05:17' },
{ timezoneCode: 'BH', timezoneName: 'Bahrain Asia/Bahrain', utcOffset: 'UTC +03:26' },
{ timezoneCode: 'BD', timezoneName: 'Bangladesh Asia/Dhaka', utcOffset: 'UTC +06:01' },
{ timezoneCode: 'BB', timezoneName: 'Barbados America/Barbados', utcOffset: 'UTC -03:58' },
{ timezoneCode: 'BY', timezoneName: 'Belarus Europe/Minsk', utcOffset: 'UTC +01:50' },
{ timezoneCode: 'BE', timezoneName: 'Belgium Europe/Brussels', utcOffset: 'UTC +00:17' },
{ timezoneCode: 'BZ', timezoneName: 'Belize America/Belize', utcOffset: 'UTC -05:52' },
{ timezoneCode: 'BJ', timezoneName: 'Benin Africa/Porto-Novo', utcOffset: 'UTC +00:13' },
{ timezoneCode: 'BM', timezoneName: 'Bermuda Atlantic/Bermuda', utcOffset: 'UTC -04:19' },
{ timezoneCode: 'BT', timezoneName: 'Bhutan Asia/Thimphu', utcOffset: 'UTC +05:58' },
{ timezoneCode: 'BO', timezoneName: 'Bolivia, Plurinational State of America/La_Paz', utcOffset: 'UTC -04:32' },
{ timezoneCode: 'BQ', timezoneName: 'Bonaire, Sint Eustatius and Saba America/Kralendijk', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'BA', timezoneName: 'Bosnia and Herzegovina Europe/Sarajevo', utcOffset: 'UTC +01:22' },
{ timezoneCode: 'BW', timezoneName: 'Botswana Africa/Gaborone', utcOffset: 'UTC +02:10' },
{ timezoneCode: 'BR', timezoneName: 'Brazil America/Araguaina', utcOffset: 'UTC -03:12' },
{ timezoneCode: 'BR', timezoneName: 'Brazil America/Bahia', utcOffset: 'UTC -02:34' },
{ timezoneCode: 'BR', timezoneName: 'Brazil America/Belem', utcOffset: 'UTC -03:13' },
{ timezoneCode: 'BR', timezoneName: 'Brazil America/Boa_Vista', utcOffset: 'UTC -04:02' },
{ timezoneCode: 'BR', timezoneName: 'Brazil America/Campo_Grande', utcOffset: 'UTC -03:38' },
{ timezoneCode: 'BR', timezoneName: 'Brazil America/Cuiaba', utcOffset: 'UTC -03:44' },
{ timezoneCode: 'BR', timezoneName: 'Brazil America/Eirunepe', utcOffset: 'UTC -04:39' },
{ timezoneCode: 'BR', timezoneName: 'Brazil America/Fortaleza', utcOffset: 'UTC -02:34' },
{ timezoneCode: 'BR', timezoneName: 'Brazil America/Maceio', utcOffset: 'UTC -02:22' },
{ timezoneCode: 'BR', timezoneName: 'Brazil America/Manaus', utcOffset: 'UTC -04:00' },
{ timezoneCode: 'BR', timezoneName: 'Brazil America/Noronha', utcOffset: 'UTC -02:09' },
{ timezoneCode: 'BR', timezoneName: 'Brazil America/Porto_Velho', utcOffset: 'UTC -04:15' },
{ timezoneCode: 'BR', timezoneName: 'Brazil America/Recife', utcOffset: 'UTC -02:19' },
{ timezoneCode: 'BR', timezoneName: 'Brazil America/Rio_Branco', utcOffset: 'UTC -04:31' },
{ timezoneCode: 'BR', timezoneName: 'Brazil America/Santarem', utcOffset: 'UTC -03:38' },
{ timezoneCode: 'BR', timezoneName: 'Brazil America/Sao_Paulo', utcOffset: 'UTC -03:06' },
{ timezoneCode: 'IO', timezoneName: 'British Indian Ocean Territory Indian/Chagos', utcOffset: 'UTC +04:49' },
{ timezoneCode: 'BN', timezoneName: 'Brunei Darussalam Asia/Brunei', utcOffset: 'UTC +07:39' },
{ timezoneCode: 'BG', timezoneName: 'Bulgaria Europe/Sofia', utcOffset: 'UTC +01:33' },
{ timezoneCode: 'BF', timezoneName: 'Burkina Faso Africa/Ouagadougou', utcOffset: 'UTC -00:16' },
{ timezoneCode: 'BI', timezoneName: 'Burundi Africa/Bujumbura', utcOffset: 'UTC +02:10' },
{ timezoneCode: 'KH', timezoneName: 'Cambodia Asia/Phnom_Penh', utcOffset: 'UTC +06:42' },
{ timezoneCode: 'CM', timezoneName: 'Cameroon Africa/Douala', utcOffset: 'UTC +00:13' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Atikokan', utcOffset: 'UTC -05:18' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Blanc-Sablon', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Cambridge_Bay', utcOffset: 'UTC +00:00' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Creston', utcOffset: 'UTC -07:28' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Dawson', utcOffset: 'UTC -09:17' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Dawson_Creek', utcOffset: 'UTC -08:00' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Edmonton', utcOffset: 'UTC -07:33' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Fort_Nelson', utcOffset: 'UTC -08:10' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Glace_Bay', utcOffset: 'UTC -03:59' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Goose_Bay', utcOffset: 'UTC -04:01' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Halifax', utcOffset: 'UTC -04:14' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Inuvik', utcOffset: 'UTC +00:00' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Iqaluit', utcOffset: 'UTC +00:00' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Moncton', utcOffset: 'UTC -04:19' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Nipigon', utcOffset: 'UTC -05:53' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Pangnirtung', utcOffset: 'UTC +00:00' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Rainy_River', utcOffset: 'UTC -06:18' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Rankin_Inlet', utcOffset: 'UTC +00:00' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Regina', utcOffset: 'UTC -06:58' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Resolute', utcOffset: 'UTC +00:00' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/St_Johns', utcOffset: 'UTC -03:30' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Swift_Current', utcOffset: 'UTC -07:11' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Thunder_Bay', utcOffset: 'UTC -05:57' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Toronto', utcOffset: 'UTC -05:17' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Vancouver', utcOffset: 'UTC -08:12' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Whitehorse', utcOffset: 'UTC -09:00' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Winnipeg', utcOffset: 'UTC -06:28' },
{ timezoneCode: 'CA', timezoneName: 'Canada America/Yellowknife', utcOffset: 'UTC +00:00' },
{ timezoneCode: 'CV', timezoneName: 'Cape Verde Atlantic/Cape_Verde', utcOffset: 'UTC -01:34' },
{ timezoneCode: 'KY', timezoneName: 'Cayman Islands America/Cayman', utcOffset: 'UTC -05:18' },
{ timezoneCode: 'CF', timezoneName: 'Central African Republic Africa/Bangui', utcOffset: 'UTC +00:13' },
{ timezoneCode: 'TD', timezoneName: 'Chad Africa/Ndjamena', utcOffset: 'UTC +01:00' },
{ timezoneCode: 'CL', timezoneName: 'Chile America/Punta_Arenas', utcOffset: 'UTC -04:43' },
{ timezoneCode: 'CL', timezoneName: 'Chile America/Santiago', utcOffset: 'UTC -04:42' },
{ timezoneCode: 'CL', timezoneName: 'Chile Pacific/Easter', utcOffset: 'UTC -07:17' },
{ timezoneCode: 'CN', timezoneName: 'China Asia/Shanghai', utcOffset: 'UTC +08:05' },
{ timezoneCode: 'CN', timezoneName: 'China Asia/Urumqi', utcOffset: 'UTC +05:50' },
{ timezoneCode: 'CX', timezoneName: 'Christmas Island Indian/Christmas', utcOffset: 'UTC +07:02' },
{ timezoneCode: 'CC', timezoneName: 'Cocos (Keeling) Islands Indian/Cocos', utcOffset: 'UTC +06:27' },
{ timezoneCode: 'CO', timezoneName: 'Colombia America/Bogota', utcOffset: 'UTC -04:56' },
{ timezoneCode: 'KM', timezoneName: 'Comoros Indian/Comoro', utcOffset: 'UTC +02:27' },
{ timezoneCode: 'CG', timezoneName: 'Congo Africa/Brazzaville', utcOffset: 'UTC +00:13' },
{ timezoneCode: 'CD', timezoneName: 'Congo, the Democratic Republic of the Africa/Kinshasa', utcOffset: 'UTC +00:13' },
{ timezoneCode: 'CD', timezoneName: 'Congo, the Democratic Republic of the Africa/Lubumbashi', utcOffset: 'UTC +02:10' },
{ timezoneCode: 'CK', timezoneName: 'Cook Islands Pacific/Rarotonga', utcOffset: 'UTC +13:20' },
{ timezoneCode: 'CR', timezoneName: 'Costa Rica America/Costa_Rica', utcOffset: 'UTC -05:36' },
{ timezoneCode: 'HR', timezoneName: 'Croatia Europe/Zagreb', utcOffset: 'UTC +01:22' },
{ timezoneCode: 'CU', timezoneName: 'Cuba America/Havana', utcOffset: 'UTC -05:29' },
{ timezoneCode: 'CW', timezoneName: 'Curaçao America/Curacao', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'CY', timezoneName: 'Cyprus Asia/Famagusta', utcOffset: 'UTC +02:15' },
{ timezoneCode: 'CY', timezoneName: 'Cyprus Asia/Nicosia', utcOffset: 'UTC +02:13' },
{ timezoneCode: 'CZ', timezoneName: 'Czech Republic Europe/Prague', utcOffset: 'UTC +00:57' },
{ timezoneCode: 'CI', timezoneName: 'Côte d\'Ivoire Africa/ Abidjan', utcOffset: 'UTC - 00: 16' },
{ timezoneCode: 'DK', timezoneName: 'Denmark Europe/Copenhagen', utcOffset: 'UTC +00:50' },
{ timezoneCode: 'DJ', timezoneName: 'Djibouti Africa/Djibouti', utcOffset: 'UTC +02:27' },
{ timezoneCode: 'DM', timezoneName: 'Dominica America/Dominica', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'DO', timezoneName: 'Dominican Republic America/Santo_Domingo', utcOffset: 'UTC -04:39' },
{ timezoneCode: 'EC', timezoneName: 'Ecuador America/Guayaquil', utcOffset: 'UTC -05:19' },
{ timezoneCode: 'EC', timezoneName: 'Ecuador Pacific/Galapagos', utcOffset: 'UTC -05:58' },
{ timezoneCode: 'EG', timezoneName: 'Egypt Africa/Cairo', utcOffset: 'UTC +02:05' },
{ timezoneCode: 'SV', timezoneName: 'El Salvador America/El_Salvador', utcOffset: 'UTC -05:56' },
{ timezoneCode: 'GQ', timezoneName: 'Equatorial Guinea Africa/Malabo', utcOffset: 'UTC +00:13' },
{ timezoneCode: 'ER', timezoneName: 'Eritrea Africa/Asmara', utcOffset: 'UTC +02:27' },
{ timezoneCode: 'EE', timezoneName: 'Estonia Europe/Tallinn', utcOffset: 'UTC +01:39' },
{ timezoneCode: 'ET', timezoneName: 'Ethiopia Africa/Addis_Ababa', utcOffset: 'UTC +02:27' },
{ timezoneCode: 'FK', timezoneName: 'Falkland Islands (Malvinas) Atlantic/Stanley', utcOffset: 'UTC -03:51' },
{ timezoneCode: 'FO', timezoneName: 'Faroe Islands Atlantic/Faroe', utcOffset: 'UTC -00:27' },
{ timezoneCode: 'FJ', timezoneName: 'Fiji Pacific/Fiji', utcOffset: 'UTC +11:55' },
{ timezoneCode: 'FI', timezoneName: 'Finland Europe/Helsinki', utcOffset: 'UTC +01:39' },
{ timezoneCode: 'FR', timezoneName: 'France Europe/Paris', utcOffset: 'UTC +00:09' },
{ timezoneCode: 'GF', timezoneName: 'French Guiana America/Cayenne', utcOffset: 'UTC -03:29' },
{ timezoneCode: 'PF', timezoneName: 'French Polynesia Pacific/Gambier', utcOffset: 'UTC -08:59' },
{ timezoneCode: 'PF', timezoneName: 'French Polynesia Pacific/Marquesas', utcOffset: 'UTC -09:18' },
{ timezoneCode: 'PF', timezoneName: 'French Polynesia Pacific/Tahiti', utcOffset: 'UTC -09:58' },
{ timezoneCode: 'TF', timezoneName: 'French Southern Territories Indian/Kerguelen', utcOffset: 'UTC +00:00' },
{ timezoneCode: 'GA', timezoneName: 'Gabon Africa/Libreville', utcOffset: 'UTC +00:13' },
{ timezoneCode: 'GM', timezoneName: 'Gambia Africa/Banjul', utcOffset: 'UTC -00:16' },
{ timezoneCode: 'GE', timezoneName: 'Georgia Asia/Tbilisi', utcOffset: 'UTC +02:59' },
{ timezoneCode: 'DE', timezoneName: 'Germany Europe/Berlin', utcOffset: 'UTC +00:53' },
{ timezoneCode: 'DE', timezoneName: 'Germany Europe/Busingen', utcOffset: 'UTC +00:34' },
{ timezoneCode: 'GH', timezoneName: 'Ghana Africa/Accra', utcOffset: 'UTC -00:16' },
{ timezoneCode: 'GI', timezoneName: 'Gibraltar Europe/Gibraltar', utcOffset: 'UTC -00:21' },
{ timezoneCode: 'GR', timezoneName: 'Greece Europe/Athens', utcOffset: 'UTC +01:34' },
{ timezoneCode: 'GL', timezoneName: 'Greenland America/Danmarkshavn', utcOffset: 'UTC -01:14' },
{ timezoneCode: 'GL', timezoneName: 'Greenland America/Nuuk', utcOffset: 'UTC -03:26' },
{ timezoneCode: 'GL', timezoneName: 'Greenland America/Scoresbysund', utcOffset: 'UTC -01:27' },
{ timezoneCode: 'GL', timezoneName: 'Greenland America/Thule', utcOffset: 'UTC -04:35' },
{ timezoneCode: 'GD', timezoneName: 'Grenada America/Grenada', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'GP', timezoneName: 'Guadeloupe America/Guadeloupe', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'GU', timezoneName: 'Guam Pacific/Guam', utcOffset: 'UTC -14:21' },
{ timezoneCode: 'GT', timezoneName: 'Guatemala America/Guatemala', utcOffset: 'UTC -06:02' },
{ timezoneCode: 'GG', timezoneName: 'Guernsey Europe/Guernsey', utcOffset: 'UTC -00:01' },
{ timezoneCode: 'GN', timezoneName: 'Guinea Africa/Conakry', utcOffset: 'UTC -00:16' },
{ timezoneCode: 'GW', timezoneName: 'Guinea-Bissau Africa/Bissau', utcOffset: 'UTC -01:02' },
{ timezoneCode: 'GY', timezoneName: 'Guyana America/Guyana', utcOffset: 'UTC -03:52' },
{ timezoneCode: 'HT', timezoneName: 'Haiti America/Port-au-Prince', utcOffset: 'UTC -04:49' },
{ timezoneCode: 'VA', timezoneName: 'Holy See (Vatican City State) Europe/Vatican', utcOffset: 'UTC +00:49' },
{ timezoneCode: 'HN', timezoneName: 'Honduras America/Tegucigalpa', utcOffset: 'UTC -05:48' },
{ timezoneCode: 'HK', timezoneName: 'Hong Kong Asia/Hong_Kong', utcOffset: 'UTC +07:36' },
{ timezoneCode: 'HU', timezoneName: 'Hungary Europe/Budapest', utcOffset: 'UTC +01:16' },
{ timezoneCode: 'IS', timezoneName: 'Iceland Atlantic/Reykjavik', utcOffset: 'UTC -01:28' },
{ timezoneCode: 'IN', timezoneName: 'India Asia/Kolkata', utcOffset: 'UTC +05:53' },
{ timezoneCode: 'ID', timezoneName: 'Indonesia Asia/Jakarta', utcOffset: 'UTC +07:07' },
{ timezoneCode: 'ID', timezoneName: 'Indonesia Asia/Jayapura', utcOffset: 'UTC +09:22' },
{ timezoneCode: 'ID', timezoneName: 'Indonesia Asia/Makassar', utcOffset: 'UTC +07:57' },
{ timezoneCode: 'ID', timezoneName: 'Indonesia Asia/Pontianak', utcOffset: 'UTC +07:17' },
{ timezoneCode: 'IR', timezoneName: 'Iran, Islamic Republic of Asia/Tehran', utcOffset: 'UTC +03:25' },
{ timezoneCode: 'IQ', timezoneName: 'Iraq Asia/Baghdad', utcOffset: 'UTC +02:57' },
{ timezoneCode: 'IE', timezoneName: 'Ireland Europe/Dublin', utcOffset: 'UTC -00:25' },
{ timezoneCode: 'IM', timezoneName: 'Isle of Man Europe/Isle_of_Man', utcOffset: 'UTC -00:01' },
{ timezoneCode: 'IL', timezoneName: 'Israel Asia/Jerusalem', utcOffset: 'UTC +02:20' },
{ timezoneCode: 'IT', timezoneName: 'Italy Europe/Rome', utcOffset: 'UTC +00:49' },
{ timezoneCode: 'JM', timezoneName: 'Jamaica America/Jamaica', utcOffset: 'UTC -05:07' },
{ timezoneCode: 'JP', timezoneName: 'Japan Asia/Tokyo', utcOffset: 'UTC +09:18' },
{ timezoneCode: 'JE', timezoneName: 'Jersey Europe/Jersey', utcOffset: 'UTC -00:01' },
{ timezoneCode: 'JO', timezoneName: 'Jordan Asia/Amman', utcOffset: 'UTC +02:23' },
{ timezoneCode: 'KZ', timezoneName: 'Kazakhstan Asia/Almaty', utcOffset: 'UTC +05:07' },
{ timezoneCode: 'KZ', timezoneName: 'Kazakhstan Asia/Aqtau', utcOffset: 'UTC +03:21' },
{ timezoneCode: 'KZ', timezoneName: 'Kazakhstan Asia/Aqtobe', utcOffset: 'UTC +03:48' },
{ timezoneCode: 'KZ', timezoneName: 'Kazakhstan Asia/Atyrau', utcOffset: 'UTC +03:27' },
{ timezoneCode: 'KZ', timezoneName: 'Kazakhstan Asia/Oral', utcOffset: 'UTC +03:25' },
{ timezoneCode: 'KZ', timezoneName: 'Kazakhstan Asia/Qostanay', utcOffset: 'UTC +04:14' },
{ timezoneCode: 'KZ', timezoneName: 'Kazakhstan Asia/Qyzylorda', utcOffset: 'UTC +04:21' },
{ timezoneCode: 'KE', timezoneName: 'Kenya Africa/Nairobi', utcOffset: 'UTC +02:27' },
{ timezoneCode: 'KI', timezoneName: 'Kiribati Pacific/Kanton', utcOffset: 'UTC +00:00' },
{ timezoneCode: 'KI', timezoneName: 'Kiribati Pacific/Kiritimati', utcOffset: 'UTC -10:29' },
{ timezoneCode: 'KI', timezoneName: 'Kiribati Pacific/Tarawa', utcOffset: 'UTC +11:32' },
{ timezoneCode: 'KP', timezoneName: 'Korea, Democratic People\'s Republic of Asia/ Pyongyang', utcOffset: 'UTC + 08: 23' },
{ timezoneCode: 'KR', timezoneName: 'Korea, Republic of Asia/Seoul', utcOffset: 'UTC +08:27' },
{ timezoneCode: 'KW', timezoneName: 'Kuwait Asia/Kuwait', utcOffset: 'UTC +03:06' },
{ timezoneCode: 'KG', timezoneName: 'Kyrgyzstan Asia/Bishkek', utcOffset: 'UTC +04:58' },
{ timezoneCode: 'LA', timezoneName: 'Lao People\'s Democratic Republic Asia/ Vientiane', utcOffset: 'UTC + 06: 42' },
{ timezoneCode: 'LV', timezoneName: 'Latvia Europe/Riga', utcOffset: 'UTC +01:36' },
{ timezoneCode: 'LB', timezoneName: 'Lebanon Asia/Beirut', utcOffset: 'UTC +02:22' },
{ timezoneCode: 'LS', timezoneName: 'Lesotho Africa/Maseru', utcOffset: 'UTC +01:52' },
{ timezoneCode: 'LR', timezoneName: 'Liberia Africa/Monrovia', utcOffset: 'UTC -00:43' },
{ timezoneCode: 'LY', timezoneName: 'Libya Africa/Tripoli', utcOffset: 'UTC +00:52' },
{ timezoneCode: 'LI', timezoneName: 'Liechtenstein Europe/Vaduz', utcOffset: 'UTC +00:34' },
{ timezoneCode: 'LT', timezoneName: 'Lithuania Europe/Vilnius', utcOffset: 'UTC +01:41' },
{ timezoneCode: 'LU', timezoneName: 'Luxembourg Europe/Luxembourg', utcOffset: 'UTC +00:24' },
{ timezoneCode: 'MO', timezoneName: 'Macao Asia/Macau', utcOffset: 'UTC +07:34' },
{ timezoneCode: 'MK', timezoneName: 'Macedonia, the Former Yugoslav Republic of Europe/Skopje', utcOffset: 'UTC +01:22' },
{ timezoneCode: 'MG', timezoneName: 'Madagascar Indian/Antananarivo', utcOffset: 'UTC +02:27' },
{ timezoneCode: 'MW', timezoneName: 'Malawi Africa/Blantyre', utcOffset: 'UTC +02:10' },
{ timezoneCode: 'MY', timezoneName: 'Malaysia Asia/Kuala_Lumpur', utcOffset: 'UTC +06:46' },
{ timezoneCode: 'MY', timezoneName: 'Malaysia Asia/Kuching', utcOffset: 'UTC +07:21' },
{ timezoneCode: 'MV', timezoneName: 'Maldives Indian/Maldives', utcOffset: 'UTC +04:54' },
{ timezoneCode: 'ML', timezoneName: 'Mali Africa/Bamako', utcOffset: 'UTC -00:16' },
{ timezoneCode: 'MT', timezoneName: 'Malta Europe/Malta', utcOffset: 'UTC +00:58' },
{ timezoneCode: 'MH', timezoneName: 'Marshall Islands Pacific/Kwajalein', utcOffset: 'UTC +11:09' },
{ timezoneCode: 'MH', timezoneName: 'Marshall Islands Pacific/Majuro', utcOffset: 'UTC +11:24' },
{ timezoneCode: 'MQ', timezoneName: 'Martinique America/Martinique', utcOffset: 'UTC -04:04' },
{ timezoneCode: 'MR', timezoneName: 'Mauritania Africa/Nouakchott', utcOffset: 'UTC -00:16' },
{ timezoneCode: 'MU', timezoneName: 'Mauritius Indian/Mauritius', utcOffset: 'UTC +03:50' },
{ timezoneCode: 'YT', timezoneName: 'Mayotte Indian/Mayotte', utcOffset: 'UTC +02:27' },
{ timezoneCode: 'MX', timezoneName: 'Mexico America/Bahia_Banderas', utcOffset: 'UTC -07:01' },
{ timezoneCode: 'MX', timezoneName: 'Mexico America/Cancun', utcOffset: 'UTC -05:47' },
{ timezoneCode: 'MX', timezoneName: 'Mexico America/Chihuahua', utcOffset: 'UTC -07:04' },
{ timezoneCode: 'MX', timezoneName: 'Mexico America/Hermosillo', utcOffset: 'UTC -07:23' },
{ timezoneCode: 'MX', timezoneName: 'Mexico America/Matamoros', utcOffset: 'UTC -06:40' },
{ timezoneCode: 'MX', timezoneName: 'Mexico America/Mazatlan', utcOffset: 'UTC -07:05' },
{ timezoneCode: 'MX', timezoneName: 'Mexico America/Merida', utcOffset: 'UTC -05:58' },
{ timezoneCode: 'MX', timezoneName: 'Mexico America/Mexico_City', utcOffset: 'UTC -06:36' },
{ timezoneCode: 'MX', timezoneName: 'Mexico America/Monterrey', utcOffset: 'UTC -06:41' },
{ timezoneCode: 'MX', timezoneName: 'Mexico America/Ojinaga', utcOffset: 'UTC -06:57' },
{ timezoneCode: 'MX', timezoneName: 'Mexico America/Tijuana', utcOffset: 'UTC -07:48' },
{ timezoneCode: 'FM', timezoneName: 'Micronesia, Federated States of Pacific/Chuuk', utcOffset: 'UTC -13:52' },
{ timezoneCode: 'FM', timezoneName: 'Micronesia, Federated States of Pacific/Kosrae', utcOffset: 'UTC -13:08' },
{ timezoneCode: 'FM', timezoneName: 'Micronesia, Federated States of Pacific/Pohnpei', utcOffset: 'UTC -13:27' },
{ timezoneCode: 'MD', timezoneName: 'Moldova, Republic of Europe/Chisinau', utcOffset: 'UTC +01:55' },
{ timezoneCode: 'MC', timezoneName: 'Monaco Europe/Monaco', utcOffset: 'UTC +00:29' },
{ timezoneCode: 'MN', timezoneName: 'Mongolia Asia/Choibalsan', utcOffset: 'UTC +07:38' },
{ timezoneCode: 'MN', timezoneName: 'Mongolia Asia/Hovd', utcOffset: 'UTC +06:06' },
{ timezoneCode: 'MN', timezoneName: 'Mongolia Asia/Ulaanbaatar', utcOffset: 'UTC +07:07' },
{ timezoneCode: 'ME', timezoneName: 'Montenegro Europe/Podgorica', utcOffset: 'UTC +01:22' },
{ timezoneCode: 'MS', timezoneName: 'Montserrat America/Montserrat', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'MA', timezoneName: 'Morocco Africa/Casablanca', utcOffset: 'UTC -00:30' },
{ timezoneCode: 'MZ', timezoneName: 'Mozambique Africa/Maputo', utcOffset: 'UTC +02:10' },
{ timezoneCode: 'MM', timezoneName: 'Myanmar Asia/Yangon', utcOffset: 'UTC +06:24' },
{ timezoneCode: 'NA', timezoneName: 'Namibia Africa/Windhoek', utcOffset: 'UTC +01:08' },
{ timezoneCode: 'NR', timezoneName: 'Nauru Pacific/Nauru', utcOffset: 'UTC +11:07' },
{ timezoneCode: 'NP', timezoneName: 'Nepal Asia/Kathmandu', utcOffset: 'UTC +05:41' },
{ timezoneCode: 'NL', timezoneName: 'Netherlands Europe/Amsterdam', utcOffset: 'UTC +00:19' },
{ timezoneCode: 'NC', timezoneName: 'New Caledonia Pacific/Noumea', utcOffset: 'UTC +11:05' },
{ timezoneCode: 'NZ', timezoneName: 'New Zealand Pacific/Auckland', utcOffset: 'UTC +11:39' },
{ timezoneCode: 'NZ', timezoneName: 'New Zealand Pacific/Chatham', utcOffset: 'UTC +12:13' },
{ timezoneCode: 'NI', timezoneName: 'Nicaragua America/Managua', utcOffset: 'UTC -05:45' },
{ timezoneCode: 'NE', timezoneName: 'Niger Africa/Niamey', utcOffset: 'UTC +00:13' },
{ timezoneCode: 'NG', timezoneName: 'Nigeria Africa/Lagos', utcOffset: 'UTC +00:13' },
{ timezoneCode: 'NU', timezoneName: 'Niue Pacific/Niue', utcOffset: 'UTC -11:19' },
{ timezoneCode: 'NF', timezoneName: 'Norfolk Island Pacific/Norfolk', utcOffset: 'UTC +11:11' },
{ timezoneCode: 'MP', timezoneName: 'Northern Mariana Islands Pacific/Saipan', utcOffset: 'UTC -14:21' },
{ timezoneCode: 'NO', timezoneName: 'Norway Europe/Oslo', utcOffset: 'UTC +00:43' },
{ timezoneCode: 'OM', timezoneName: 'Oman Asia/Muscat', utcOffset: 'UTC +03:41' },
{ timezoneCode: 'PK', timezoneName: 'Pakistan Asia/Karachi', utcOffset: 'UTC +04:28' },
{ timezoneCode: 'PW', timezoneName: 'Palau Pacific/Palau', utcOffset: 'UTC -15:02' },
{ timezoneCode: 'PS', timezoneName: 'Palestine, State of Asia/Gaza', utcOffset: 'UTC +02:17' },
{ timezoneCode: 'PS', timezoneName: 'Palestine, State of Asia/Hebron', utcOffset: 'UTC +02:20' },
{ timezoneCode: 'PA', timezoneName: 'Panama America/Panama', utcOffset: 'UTC -05:18' },
{ timezoneCode: 'PG', timezoneName: 'Papua New Guinea Pacific/Bougainville', utcOffset: 'UTC +10:22' },
{ timezoneCode: 'PG', timezoneName: 'Papua New Guinea Pacific/Port_Moresby', utcOffset: 'UTC +09:48' },
{ timezoneCode: 'PY', timezoneName: 'Paraguay America/Asuncion', utcOffset: 'UTC -03:50' },
{ timezoneCode: 'PE', timezoneName: 'Peru America/Lima', utcOffset: 'UTC -05:08' },
{ timezoneCode: 'PH', timezoneName: 'Philippines Asia/Manila', utcOffset: 'UTC -15:56' },
{ timezoneCode: 'PN', timezoneName: 'Pitcairn Pacific/Pitcairn', utcOffset: 'UTC -08:40' },
{ timezoneCode: 'PL', timezoneName: 'Poland Europe/Warsaw', utcOffset: 'UTC +01:24' },
{ timezoneCode: 'PT', timezoneName: 'Portugal Atlantic/Azores', utcOffset: 'UTC -01:42' },
{ timezoneCode: 'PT', timezoneName: 'Portugal Atlantic/Madeira', utcOffset: 'UTC -01:07' },
{ timezoneCode: 'PT', timezoneName: 'Portugal Europe/Lisbon', utcOffset: 'UTC -00:36' },
{ timezoneCode: 'PR', timezoneName: 'Puerto Rico America/Puerto_Rico', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'QA', timezoneName: 'Qatar Asia/Qatar', utcOffset: 'UTC +03:26' },
{ timezoneCode: 'RO', timezoneName: 'Romania Europe/Bucharest', utcOffset: 'UTC +01:44' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Anadyr', utcOffset: 'UTC +11:49' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Barnaul', utcOffset: 'UTC +05:35' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Chita', utcOffset: 'UTC +07:33' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Irkutsk', utcOffset: 'UTC +06:57' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Kamchatka', utcOffset: 'UTC +10:34' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Khandyga', utcOffset: 'UTC +09:02' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Krasnoyarsk', utcOffset: 'UTC +06:11' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Magadan', utcOffset: 'UTC +10:03' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Novokuznetsk', utcOffset: 'UTC +05:48' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Novosibirsk', utcOffset: 'UTC +05:31' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Omsk', utcOffset: 'UTC +04:53' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Sakhalin', utcOffset: 'UTC +09:30' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Srednekolymsk', utcOffset: 'UTC +10:14' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Tomsk', utcOffset: 'UTC +05:39' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Ust-Nera', utcOffset: 'UTC +09:32' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Vladivostok', utcOffset: 'UTC +08:47' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Yakutsk', utcOffset: 'UTC +08:38' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Asia/Yekaterinburg', utcOffset: 'UTC +04:02' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Europe/Astrakhan', utcOffset: 'UTC +03:12' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Europe/Kaliningrad', utcOffset: 'UTC +01:22' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Europe/Kirov', utcOffset: 'UTC +03:18' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Europe/Moscow', utcOffset: 'UTC +02:30' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Europe/Samara', utcOffset: 'UTC +03:20' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Europe/Saratov', utcOffset: 'UTC +03:04' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Europe/Ulyanovsk', utcOffset: 'UTC +03:13' },
{ timezoneCode: 'RU', timezoneName: 'Russian Federation Europe/Volgograd', utcOffset: 'UTC +02:57' },
{ timezoneCode: 'RW', timezoneName: 'Rwanda Africa/Kigali', utcOffset: 'UTC +02:10' },
{ timezoneCode: 'RE', timezoneName: 'Réunion Indian/Reunion', utcOffset: 'UTC +03:41' },
{ timezoneCode: 'BL', timezoneName: 'Saint Barthélemy America/St_Barthelemy', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'SH', timezoneName: 'Saint Helena, Ascension and Tristan da Cunha Atlantic/St_Helena', utcOffset: 'UTC -00:16' },
{ timezoneCode: 'KN', timezoneName: 'Saint Kitts and Nevis America/St_Kitts', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'LC', timezoneName: 'Saint Lucia America/St_Lucia', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'MF', timezoneName: 'Saint Martin (French part) America/Marigot', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'PM', timezoneName: 'Saint Pierre and Miquelon America/Miquelon', utcOffset: 'UTC -03:44' },
{ timezoneCode: 'VC', timezoneName: 'Saint Vincent and the Grenadines America/St_Vincent', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'WS', timezoneName: 'Samoa Pacific/Apia', utcOffset: 'UTC +12:33' },
{ timezoneCode: 'SM', timezoneName: 'San Marino Europe/San_Marino', utcOffset: 'UTC +00:49' },
{ timezoneCode: 'ST', timezoneName: 'Sao Tome and Principe Africa/Sao_Tome', utcOffset: 'UTC +00:26' },
{ timezoneCode: 'SA', timezoneName: 'Saudi Arabia Asia/Riyadh', utcOffset: 'UTC +03:06' },
{ timezoneCode: 'SN', timezoneName: 'Senegal Africa/Dakar', utcOffset: 'UTC -00:16' },
{ timezoneCode: 'RS', timezoneName: 'Serbia Europe/Belgrade', utcOffset: 'UTC +01:22' },
{ timezoneCode: 'SC', timezoneName: 'Seychelles Indian/Mahe', utcOffset: 'UTC +03:41' },
{ timezoneCode: 'SL', timezoneName: 'Sierra Leone Africa/Freetown', utcOffset: 'UTC -00:16' },
{ timezoneCode: 'SG', timezoneName: 'Singapore Asia/Singapore', utcOffset: 'UTC +06:55' },
{ timezoneCode: 'SX', timezoneName: 'Sint Maarten (Dutch part) America/Lower_Princes', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'SK', timezoneName: 'Slovakia Europe/Bratislava', utcOffset: 'UTC +00:57' },
{ timezoneCode: 'SI', timezoneName: 'Slovenia Europe/Ljubljana', utcOffset: 'UTC +01:22' },
{ timezoneCode: 'SB', timezoneName: 'Solomon Islands Pacific/Guadalcanal', utcOffset: 'UTC +10:39' },
{ timezoneCode: 'SO', timezoneName: 'Somalia Africa/Mogadishu', utcOffset: 'UTC +02:27' },
{ timezoneCode: 'ZA', timezoneName: 'South Africa Africa/Johannesburg', utcOffset: 'UTC +01:52' },
{
  timezoneCode: 'GS', timezoneName: 'South Georgia and the South Sandwich Islands Atlantic/South_Georgia', utcOffset: 'UTC -02:26'
},
  , { timezoneCode: 'SS', timezoneName: 'South Sudan Africa/ Juba', utcOffset: 'UTC + 02: 06' },
{ timezoneCode: 'ES', timezoneName: 'Spain Africa/Ceuta', utcOffset: 'UTC -00:21' },
{ timezoneCode: 'ES', timezoneName: 'Spain Atlantic/Canary', utcOffset: 'UTC -01:01' },
{ timezoneCode: 'ES', timezoneName: 'Spain Europe/Madrid', utcOffset: 'UTC -00:14' },
{ timezoneCode: 'LK', timezoneName: 'Sri Lanka Asia/Colombo', utcOffset: 'UTC +05:19' },
{ timezoneCode: 'SD', timezoneName: 'Sudan Africa/Khartoum', utcOffset: 'UTC +02:10' },
{ timezoneCode: 'SR', timezoneName: 'Suriname America/Paramaribo', utcOffset: 'UTC -03:40' },
{ timezoneCode: 'SJ', timezoneName: 'Svalbard and Jan Mayen Arctic/Longyearbyen', utcOffset: 'UTC +00:43' },
{ timezoneCode: 'SZ', timezoneName: 'Swaziland Africa/Mbabane', utcOffset: 'UTC +01:52' },
{ timezoneCode: 'SE', timezoneName: 'Sweden Europe/Stockholm', utcOffset: 'UTC +01:12' },
{ timezoneCode: 'CH', timezoneName: 'Switzerland Europe/Zurich', utcOffset: 'UTC +00:34' },
{ timezoneCode: 'SY', timezoneName: 'Syrian Arab Republic Asia/Damascus', utcOffset: 'UTC +02:25' },
{ timezoneCode: 'TW', timezoneName: 'Taiwan, Province of China Asia/Taipei', utcOffset: 'UTC +08:06' },
{ timezoneCode: 'TJ', timezoneName: 'Tajikistan Asia/Dushanbe', utcOffset: 'UTC +04:35' },
{ timezoneCode: 'TZ', timezoneName: 'Tanzania, United Republic of Africa/Dar_es_Salaam', utcOffset: 'UTC +02:27' },
{ timezoneCode: 'TH', timezoneName: 'Thailand Asia/Bangkok', utcOffset: 'UTC +06:42' },
{ timezoneCode: 'TL', timezoneName: 'Timor-Leste Asia/Dili', utcOffset: 'UTC +08:22' },
{ timezoneCode: 'TG', timezoneName: 'Togo Africa/Lome', utcOffset: 'UTC -00:16' },
{ timezoneCode: 'TK', timezoneName: 'Tokelau Pacific/Fakaofo', utcOffset: 'UTC -11:24' },
{ timezoneCode: 'TO', timezoneName: 'Tonga Pacific/Tongatapu', utcOffset: 'UTC +12:19' },
{ timezoneCode: 'TT', timezoneName: 'Trinidad and Tobago America/Port_of_Spain', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'TN', timezoneName: 'Tunisia Africa/Tunis', utcOffset: 'UTC +00:40' },
{ timezoneCode: 'TR', timezoneName: 'Turkey Europe/Istanbul', utcOffset: 'UTC +01:55' },
{ timezoneCode: 'TM', timezoneName: 'Turkmenistan Asia/Ashgabat', utcOffset: 'UTC +03:53' },
{ timezoneCode: 'TC', timezoneName: 'Turks and Caicos Islands America/Grand_Turk', utcOffset: 'UTC -04:44' },
{ timezoneCode: 'TV', timezoneName: 'Tuvalu Pacific/Funafuti', utcOffset: 'UTC +11:56' },
{ timezoneCode: 'UG', timezoneName: 'Uganda Africa/Kampala', utcOffset: 'UTC +02:27' },
{ timezoneCode: 'UA', timezoneName: 'Ukraine Europe/Kiev', utcOffset: 'UTC +02:02' },
{ timezoneCode: 'UA', timezoneName: 'Ukraine Europe/Simferopol', utcOffset: 'UTC +02:16' },
{ timezoneCode: 'UA', timezoneName: 'Ukraine Europe/Uzhgorod', utcOffset: 'UTC +01:29' },
{ timezoneCode: 'UA', timezoneName: 'Ukraine Europe/Zaporozhye', utcOffset: 'UTC +02:20' },
{ timezoneCode: 'AE', timezoneName: 'United Arab Emirates Asia/Dubai', utcOffset: 'UTC +03:41' },
{ timezoneCode: 'GB', timezoneName: 'United Kingdom Europe/London', utcOffset: 'UTC -00:01' },
{ timezoneCode: 'US', timezoneName: 'United States America/Adak', utcOffset: 'UTC +12:13' },
{ timezoneCode: 'US', timezoneName: 'United States America/Anchorage', utcOffset: 'UTC +14:00' },
{ timezoneCode: 'US', timezoneName: 'United States America/Boise', utcOffset: 'UTC -07:44' },
{ timezoneCode: 'US', timezoneName: 'United States America/Chicago', utcOffset: 'UTC -05:50' },
{ timezoneCode: 'US', timezoneName: 'United States America/Denver', utcOffset: 'UTC -06:59' },
{ timezoneCode: 'US', timezoneName: 'United States America/Detroit', utcOffset: 'UTC -05:32' },
{ timezoneCode: 'US', timezoneName: 'United States America/Indiana/Indianapolis', utcOffset: 'UTC -05:44' },
{ timezoneCode: 'US', timezoneName: 'United States America/Indiana/Knox', utcOffset: 'UTC -05:46' },
{ timezoneCode: 'US', timezoneName: 'United States America/Indiana/Marengo', utcOffset: 'UTC -05:45' },
{ timezoneCode: 'US', timezoneName: 'United States America/Indiana/Petersburg', utcOffset: 'UTC -05:49' },
{ timezoneCode: 'US', timezoneName: 'United States America/Indiana/Tell_City', utcOffset: 'UTC -05:47' },
{ timezoneCode: 'US', timezoneName: 'United States America/Indiana/Vevay', utcOffset: 'UTC -05:40' },
{ timezoneCode: 'US', timezoneName: 'United States America/Indiana/Vincennes', utcOffset: 'UTC -05:50' },
{ timezoneCode: 'US', timezoneName: 'United States America/Indiana/Winamac', utcOffset: 'UTC -05:46' },
{ timezoneCode: 'US', timezoneName: 'United States America/Juneau', utcOffset: 'UTC +15:02' },
{ timezoneCode: 'US', timezoneName: 'United States America/Kentucky/Louisville', utcOffset: 'UTC -05:43' },
{ timezoneCode: 'US', timezoneName: 'United States America/Kentucky/Monticello', utcOffset: 'UTC -05:39' },
{ timezoneCode: 'US', timezoneName: 'United States America/Los_Angeles', utcOffset: 'UTC -07:52' },
{ timezoneCode: 'US', timezoneName: 'United States America/Menominee', utcOffset: 'UTC -05:50' },
{ timezoneCode: 'US', timezoneName: 'United States America/Metlakatla', utcOffset: 'UTC +15:13' },
{ timezoneCode: 'US', timezoneName: 'United States America/New_York', utcOffset: 'UTC -04:56' },
{ timezoneCode: 'US', timezoneName: 'United States America/Nome', utcOffset: 'UTC +12:58' },
{ timezoneCode: 'US', timezoneName: 'United States America/North_Dakota/Beulah', utcOffset: 'UTC -06:47' },
{ timezoneCode: 'US', timezoneName: 'United States America/North_Dakota/Center', utcOffset: 'UTC -06:45' },
{ timezoneCode: 'US', timezoneName: 'United States America/North_Dakota/New_Salem', utcOffset: 'UTC -06:45' },
{ timezoneCode: 'US', timezoneName: 'United States America/Phoenix', utcOffset: 'UTC -07:28' },
{ timezoneCode: 'US', timezoneName: 'United States America/Sitka', utcOffset: 'UTC +14:58' },
{ timezoneCode: 'US', timezoneName: 'United States America/Yakutat', utcOffset: 'UTC +14:41' },
{ timezoneCode: 'US', timezoneName: 'United States Pacific/Honolulu', utcOffset: 'UTC -10:31' },
{ timezoneCode: 'UM', timezoneName: 'United States Minor Outlying Islands Pacific/Midway', utcOffset: 'UTC +12:37' },
{ timezoneCode: 'UM', timezoneName: 'United States Minor Outlying Islands Pacific/Wake', utcOffset: 'UTC +11:06' },
{ timezoneCode: 'UY', timezoneName: 'Uruguay America/Montevideo', utcOffset: 'UTC -03:44' },
{ timezoneCode: 'UZ', timezoneName: 'Uzbekistan Asia/Samarkand', utcOffset: 'UTC +04:27' },
{ timezoneCode: 'UZ', timezoneName: 'Uzbekistan Asia/Tashkent', utcOffset: 'UTC +04:37' },
{ timezoneCode: 'VU', timezoneName: 'Vanuatu Pacific/Efate', utcOffset: 'UTC +11:13' },
{ timezoneCode: 'VE', timezoneName: 'Venezuela, Bolivarian Republic of America/Caracas', utcOffset: 'UTC -04:27' },
{ timezoneCode: 'VN', timezoneName: 'Viet Nam Asia/Ho_Chi_Minh', utcOffset: 'UTC +07:06' },
{ timezoneCode: 'VG', timezoneName: 'Virgin Islands, British America/Tortola', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'VI', timezoneName: 'Virgin Islands, U.S. America/St_Thomas', utcOffset: 'UTC -04:24' },
{ timezoneCode: 'WF', timezoneName: 'Wallis and Futuna Pacific/Wallis', utcOffset: 'UTC +12:15' },
{ timezoneCode: 'EH', timezoneName: 'Western Sahara Africa/El_Aaiun', utcOffset: 'UTC -00:52' },
{ timezoneCode: 'YE', timezoneName: 'Yemen Asia/Aden', utcOffset: 'UTC +03:06' },
{ timezoneCode: 'ZM', timezoneName: 'Zambia Africa/Lusaka', utcOffset: 'UTC +02:10' },
{ timezoneCode: 'ZW', timezoneName: 'Zimbabwe Africa/Harare', utcOffset: 'UTC +02:10' },
{ timezoneCode: 'AX', timezoneName: 'Åland Islands Europe/Mariehamn', utcOffset: 'UTC +01:39' }]